### ISSUE TITLE
Question about get authorization code

### ISSUE THREAD

**Issue by screenleon** [Yuhsak/line-api#2]
Thought I dont have an access token, I need to use authorize() method to get the code and ask for access token.
But class Notify's constructor need access token to constructor. 
Then how can I get the access token by oauth2?

**Comment by yuhsak** [comment]
@screenleon 
You need to generate a specific access token first when you start using LINE Notify API.
I probably should refer to this url at README for convenience. Thanks for asking.

[https://notify-bot.line.me/en/](https://notify-bot.line.me/en/)
